# 十一、错误处理

错误处理是 PHP 5.6 和 PHP 7.1 之间一些最大变化的原因，尽管我们在本书的其他相关地方已经提到了这个重要的话题，但是单独讨论它还是有意义的。

## 可投掷物品

在本章中，我们将会看到`Error`和`Exception`类。现在，你需要知道的是它们都实现了 PHP 7 中引入的`Throwable`接口。

Tip

PHP 定义一个新的不扩展`Exception`类的`Error`类的原因是为了保持与 PHP5.6 代码的向后兼容性。

### 可抛出的界面

异常和错误异常都实现了`Throwable`接口，所以您可以在一个块中捕获这两种类型，如下所示:

```php
<?php
try {
    // ...code

} catch (Throwable $e) {
    echo "A class that inherits from either Exception or ErrorException was caught";
}

```

一会儿我们将看到 PHP 用来比较`ErrorExceptions`和`Exceptions`与`catch`块的匹配规则。

你可以在 PHP 手册的`Throwable`接口中找到定义的方法， <sup>1</sup> 但是为了你的方便，这里把它们列出来:

```php
Throwable {
/* Methods */
abstract public string getMessage ( void )
abstract public int getCode ( void )
abstract public string getFile ( void )
abstract public int getLine ( void )
abstract public array getTrace ( void )
abstract public string getTraceAsString ( void )
abstract public Throwable getPrevious ( void )
abstract public string __toString ( void )
}

```

Tip

这些方法对于记录错误非常有用。

## 错误

在 PHP 的旧版本中，错误和异常的处理方式非常不同。错误是引擎中产生的东西，只要它不是致命的，就可以由用户定义的函数来处理。

问题是有几个错误是致命的，无法由用户定义的错误处理程序来处理。

这意味着你不能优雅地处理 PHP5.6 中的致命错误。有几个副作用是有问题的——比如运行时上下文的丢失，析构函数不会被调用，以及处理它们很笨拙。

在 PHP 7 中，致命错误现在是异常，并且更容易处理。

Note

只有致命错误才会引发错误异常。您需要用错误处理函数来处理非致命错误。

下面是一个在 PHP 7.1 中捕捉致命错误的例子。请注意非致命错误是如何被捕获的。

```php
<?php
try {
    // generates a notice error (not caught)
    echo $thisVariableIsNotSet;
    // this would be a fatal error (is caught)
    badFunction();
} catch (Error $e) {
    echo "Error caught: " . $e->getMessage();
}

```

如果试图访问无效变量，该脚本将输出一个错误通知。在 PHP 的早期版本中，试图调用一个不存在的函数会导致致命错误，但是在 PHP 7.1 中，您可以发现它。

以下是该脚本的输出:

```php
Notice: Undefined variable: thisVariableIsNotSet in /in/lQC3F on line 5
Error caught: Call to undefined function badFunction()

```

### 误差常数

PHP 有很多与错误相关的常量 <sup>2</sup> 。这些常量在配置 PHP 来隐藏或显示某些类的错误时使用。

以下是一些更常见的错误代码:

    
| 密码 | 描述 | 脚本 | 抛出错误？ |
| --- | --- | --- | --- |
| `E_DEPRECATED` | 如果您使用不推荐使用的语言功能，解释器将生成这种类型的警告。 | 继续运行 | 不 |
| `E_STRICT` | 与`E_DEPRECATED`类似，这表明您正在使用一种当前不标准的语言特性，将来可能无法工作。 | 继续运行 | 不 |
| `E_PARSE` | 无法解析您的语法，因此您的脚本无法启动。 | 根本不会跑 | 不 |
| `E_NOTICE` | 信息性消息。 | 继续运行 | 不 |
| `E_WARNING` | 这些是非致命警告。 | 继续运行 | 不 |
| `E_ERROR` | 脚本无法继续运行，正在被终止。 | 中止，除非您用错误处理程序来处理它 | 是 |
| `E_RECOVERABLE_ERROR` | 这个错误可能足够危险，足以致命，但引擎并没有处于无法继续运行的状态。 | 中止，除非您用错误处理程序来处理它 | 是 |

### 使用错误处理函数

`set_error_handler()`函数 <sup>3</sup> 用于告诉 PHP 如何处理不是`Error`异常类实例的标准引擎错误。对于致命错误，不能使用错误处理函数；你必须抓住他们作为`Error`的例外。

`set_error_handler()`接受一个可调用的 <sup>4</sup> 作为其参数。PHP 中的可调用函数有两种指定方式:一种是表示函数名的字符串，另一种是传递包含对象和方法名的数组(按此顺序)。

Note

您可以将对象中的受保护方法和私有方法指定为可调用的。

还可以传递 null 来告诉 PHP 使用标准的错误处理机制。

如果您的错误处理程序没有终止程序并返回，那么您的脚本将在错误发生后的行继续执行。

PHP 将参数传递给错误处理函数。如果想在函数中使用它们，可以选择在函数签名中声明它们。

```php
<?php

function myHandler(int $errNo, string $errMsg, string $file, int $line) {
    echo "Error #[$errNo] occurred in [$file] at line [$line]: [$errMsg]";
}

set_error_handler('myHandler');

try {
  // This does not throw an Error
  5 / 0;
} catch ( Throwable $e ) {
  echo 'Caught error : ' . $e->getMessage();
}

/*
  Error #[2] occurred in [/in/Xa0Td] at line [11]: [Division by zero]
*/

```

在前面的例子中，我们将数字五除以零。在 PHP 中，这会导致警告，所以不会抛出`Error`。然而，我们已经将函数`myHandler()`设置为客户错误处理程序，因此当 PHP 遇到警告时会调用它。

用户错误处理程序无法捕获导致脚本终止的错误；这些包括`E_ERROR`、`E_PARSE`、`E_CORE_ERROR`、`E_CORE_WARNING`、`E_COMPILE_ERROR`和`E_COMPILE_WARNING`。

### 显示或抑制非致命错误消息

通常，您希望在生产过程中隐藏所有系统错误消息，并且您的代码应该在不生成警告或消息的情况下运行。如果您要显示一条错误消息，请确保它是您自己生成的，并且不包含可能帮助攻击者侵入您的系统的信息。

在您的开发环境中，您希望显示所有错误，以便您可以修复与它们相关的所有问题，但是在生产环境中，您希望禁止向用户发送任何系统消息。

为此，您需要在您的`php.ini`文件中使用以下设置来配置 PHP:

*   `display_errors`可设置为 false 以抑制消息
*   `log_errors`可用于在日志文件中存储错误信息
*   可以设置`error_reporting`来配置哪些错误触发报告

最佳实践是优雅地处理应用中的错误。在生产中，您应该记录未处理的错误，而不是允许它们显示给用户。

Note

我们在第一章中看到了错误抑制运算符`@`。记住最好避免使用它。

`error_log()`函数 <sup>5</sup> 可用于向系统错误处理程序之一发送消息。您不应该将它与`error_log`配置选项混淆。配置选项指定如何处理日志，而函数用于发送消息。

你也可以使用`error_log()`函数来发送电子邮件，但就我个人而言，我不会这样做，我宁愿用代码或使用类似滚动条的服务来实现。 <sup>6</sup>

### 错误处理功能

PHP 有很多与错误处理相关的函数<sup>7</sup><sup>8</sup>。下表提供了它们的摘要。在这一章中，我们将会看到其中的大部分。

  
| 功能 | 目的 |
| --- | --- |
| `debug_backtrace` | 生成回溯。 |
| 调试 _ 打印 _ 回溯 | 打印回溯。使用该函数时要小心，因为它会产生大量输出！ |
| `error_clear_last` | 清除最近的错误。 |
| `error_get_last` | 获取最后发生的错误。 |
| `error_log` | 向定义的错误处理例程发送错误消息。 |
| `error_reporting` | 设置报告哪些 PHP 错误。 |
| 还原错误处理程序 | 恢复以前的错误处理函数。 |
| 还原异常处理程序 | 恢复先前定义的异常处理函数。 |
| 设置错误处理程序 | 设置用户定义的错误处理函数。 |
| 设置异常处理程序 | 设置用户定义的异常处理函数。 |
| 触发器 _ 错误 | 生成用户级错误/警告/通知消息。 |
| 用户 _ 错误 | `trigger_error`的别名。 |

## 例外

异常是面向对象编程的核心部分，最初是在 PHP 5.0 中引入的。异常是一个程序状态，它需要特殊的处理，因为它没有以预期的方式运行。

你可以使用一个异常来改变程序的流程，例如，如果不满足某些前提条件，就停止做一些事情。

如果您没有捕捉到异常，它就会在调用堆栈中冒泡。让我们看一个例子:

```php
<?php
function A() {
  // The exception thrown in C will bubble up to A
  // because it is not handled in C or B
  try {
    B();
  } catch (Exception $e) {
    echo "Caught exception in " . __METHOD__;
  }
}

function B() {
  // we're not catching exceptions in B
  C();
}

function C() {
  // we do not catch the exception where it is thrown
  throw new Exception('Bubble');
}
A();
/*
Outputs:
  Caught exception in A and the program ends successfully
*/

```

这个程序调用函数 A，函数 A 调用 B，B 调用 C。函数 C 抛出一个异常，但是我们没有在 C 中捕捉到它。异常冒泡到 B，但是也没有在 B 中捕捉到。异常继续冒泡到 A，在那里我们确实捕捉到了它。

如果我们没有在 A 中捕捉到异常，那么它将会冒泡到全局范围，在那里我们将有最后一次捕捉它的机会。如果一个异常没有被捕获，那么 PHP 会寻找一个默认的异常处理程序，最终如果没有处理程序，就会导致一个致命的错误。

### 扩展异常类

PHP 包括几个标准的异常类型，标准 PHP 库(SPL)还包括更多。虽然您不必使用这些异常，但是这样做意味着您可以使用更细粒度的错误检测和报告。

`Exception`和`Error`类都实现了`Throwable`接口 <sup>9</sup> ，并且像任何其他类一样，可以被扩展。这允许您创建灵活的错误层次结构，并定制您的异常处理。

只有实现了`Throwable`类的类才能与`throw`关键字一起使用。换句话说，你不能声明你自己的基类，然后把它作为异常抛出。

例如，让我们创建一个异常类，我们可以用它来表示出现了表单验证问题:

```php
<?php
class ValidationException extends Exception { }

function myValidation() {
    if (empty($_POST)) {
        throw new ValidationException('No form fields entered');
    }
}

```

让我们看看语法，然后更详细地讨论异常:

```php
<?php
class ParentException extends Exception {}
class ChildException extends ParentException {}

try {
    // some code
    throw new ChildException('My Message');
} catch (ParentException $e) {
    // matches this class because of inheritance
    echo "Parent Exception :" . $e->getMessage();
} catch (ChildException $e) {
    // matches this class exactly
    echo "Child Exception :" . $e->getMessage();
} catch (Exception $e) {
    // matches this class because of inheritance
    echo "Exception :" . $e->getMessage();
}

```

这个例子的输出是`Parent Exception :My Message`。

在这个例子中，我们抛出了一个继承自`ParentException`的`ChildException`，它又扩展了基类`Exception`。

这些块按照从上到下的顺序进行评估。将执行第一个匹配的块。

被抛出的异常的类与作为参数给定给`catch`子句的类名相匹配。

匹配标准是这些类别是:

*   完全一样，或者
*   抛出的异常是`catch`语句中异常的祖先

在这个例子中，我们抛出了一个继承自`ParentException`的异常`ChildException`。因此，异常与第一个`catch`块匹配，代码被执行。

我将基`Exception`放在了`catch`块列表的底部，因为所有自定义异常都继承自它，这使得它成为一个总括。

### 异常层次结构

到目前为止，我们已经知道`Errors`和`Exceptions`都实现了`Throwable`接口。我们刚刚看到`Error`和`Exception`类都可以扩展。

内置的 PHP 7 异常层次结构如下所示:

```php
interface Throwable
    |- Exception implements Throwable
        |- ...
    |- Error implements Throwable
        |- TypeError extends Error
            |- ArgumentCountError
        |- ParseError extends Error
        |- ArithmeticError extends Error
            |- DivisionByZeroError extends ArithmeticError
        |- AssertionError extends Error

```

正如您所看到的，有几个预定义的错误类在`Error`下面形成了一个层次结构。下表总结了它们的用途:

  
| 班级 | 目的 |
| --- | --- |
| `TypeError` | 当传递给函数的参数与其对应的声明参数类型不匹配时，或者当函数没有返回预期的类型时，就会抛出`TypeError`。 |
| `ArgumentCountError` | 当传递给用户定义的函数或方法的参数太少时，抛出`ArgumentCountError`。 |
| `ParseError` | 当解析 PHP 代码时出现错误，例如，当您调用`eval()`或包含一个文件时，就会抛出一个`ParseError`。 |
| `ArithmeticError` | 当您尝试以负的量进行位移位或调用`intdiv()`时，会发生算术错误，这将导致当前系统上的值超出整数的限制。 |
| `DivisionByZeroError` | 如果你试图除以零，就会出现一个`DivisionByZeroError`。 |
| `AssertionError` | 当用`assert()`语言构造的断言失败时，抛出一个`AssertionError`。 |

## 处理异常

健壮的代码可以遇到错误并处理它。以明智的方式处理异常提高了应用的安全性，并使日志记录和调试更加容易。管理应用中的错误还可以让您为用户提供更好的体验。在这一节中，我们将介绍如何捕获和处理代码中出现的错误。

### 捕捉异常

记得在本章的前面，我们这样定义了一个`ValidationException`:

```php
<?php
class ValidationException extends Exception { }

function myValidation() {
    if (empty($_POST)) {
        throw new ValidationException('No form fields entered');
    }
}

```

让我们从那里继续，想象我们正在调用`myValidation()`函数，并且想要捕捉异常。捕捉异常的语法如下:

```php
<?php
try {
    // assume that if there is validation problem this throws a ValidationException
    myValidation();
} catch (ValidationException $e) {
    echo "Validation exception caught ";
    echo $e->getMessage();
} catch (Exception $e) {
    echo "General exception type caught";
}

```

注意这里有两个`catch`子句。异常将从上到下与子句匹配，直到异常的类型与`catch`子句匹配。

Note

匹配标准是这些类要么完全相同，要么抛出的异常类是`catch`语句中`Exception`类的祖先。

由于`myValidation`抛出了一个`ValidationException`，我们期望它在第一个块中被捕获，但是如果函数中抛出了任何其他类型的异常，那么它将在第二个`catch`块中被捕获。

还要注意方法`getMessage()`正在异常对象上被调用。基本`Exception`类中的其他方法将给出错误代码、堆栈跟踪和其他信息。关于`Exceptions` <sup>11</sup> 的 PHP 手册对于异常对象的原型是最好的参考。

有可能在`catch`块中抛出异常。这使您可以捕捉异常，然后在需要时将其作为不同的类型重新抛出。

Tip

你应该总是把你的`catch`块从最具体的排在顶部，到最一般的排在底部——记住`catch`块是贪婪的！

一个`catch`块可以指定多个异常类，用管道字符(|)分隔它们。

在下面的例子中，`catch`块将匹配属于`MyException`类或`AnotherException`类的异常。

```php
<?php

class MyException extends Exception {}
class AnotherException extends Exception {}

try {
    throw new AnotherException;
} catch (MyException | AnotherException $e) {
    echo "Caught : " . get_class($e);
}
/*
Caught : AnotherException
*/

```

Note

一个`try`块必须至少有一个`catch`块。

### 最终块

我们要看的最后一个子句是`finally`。无论是否抛出异常，这段代码都将被执行。它在`try`程序块完成后或异常程序块完成后执行。

`finally`块的一个常见用途是关闭一个文件句柄，但是`finally`可以用在您希望代码总是被执行的任何地方。

```php
<?php
try {
  // perform some functions
} catch (Exception $e) {
  // handle the error
} finally {
  // always run these statements
}

```

### 设置默认异常处理程序

任何未被捕获的异常都会导致致命错误。如果您想优雅地响应没有被`catch`块捕获的异常，那么您需要设置一个函数作为默认的异常处理程序。

为此，您可以使用`set_exception_handler()`函数，该函数接受一个 callable 作为其参数。您的脚本将在 callable 执行后终止。

函数`restore_exception_handler()`会将异常处理程序恢复到之前的值。

Chapter 11 Quiz

Q1:这段代码会输出什么？

 
| 发现错误！ |
| 作为会话 ID 的随机字符串 |
| 一个通知错误和一个警告 |
| 两行格式化的行，每一行包含关于错误的信息 |

```php
<?php
$handler = function($errorNumber, $errorMessage, $file, $line) {
  echo "Error [$errorNumber] in [$file] at line [$line]: '[$errorMessage]'\r\n";
};
set_error_handler($handler);
try {
    echo $a;
    session_start();
    echo session_id();
} catch (Throwable $e) {
    echo "Error caught!";
}

```

Q2:这段代码会输出什么？

 
| 没有，这运行没有错误 |
| 一个正常的致命错误 PHP 消息 |
| 关于错误的格式化信息行 |
| 以上都不是 |

```php
<?php
$handler = function($errorNumber, $errorMessage, $file, $line) {
  echo "Error [$errorNumber] in [$file] at line [$line]: '[$errorMessage]'\r\n";
};
set_error_handler($handler);
this_function_is_not_defined();

```

Q3:这段代码会输出什么？

 
| 没有，这段代码运行没有错误 |
| 哎呀！ |
| 一个 PHP 致命错误 |
| 以上都不是 |

```php
<?php
class IndianaError extends ArithmeticError {}
define('PI', 3);
try {
    if (is_int(PI)) {
      throw new IndianaError('Oops');
    }
} catch (Exception $e) {
    echo $e->getMessage();
}

```

Q4:这段代码会输出什么？

 
| 你好世界 |
| 两行信息 |
| 一个 PHP 致命错误 |
| 以上都不是 |

```php
<?php
set_error_handler(function($errorNumber, $errorMessage, $file, $line) {
  debug_print_backtrace();
});
trigger_error('Hello world', E_USER_WARNING);

```

Q5:这段代码会输出什么？

 
| 捕获到异常！ |
| 接住了！ |
| 发现错误！ |
| `DivisionByZeroError`抓到了！ |
| 以上都不是 |

```php
<?php
try {
    echo 50/0;
} catch (Exception $e) {
    echo "Exception caught!";
} catch (Throwable $e) {
    echo " Throwable caught!";
} catch (Error $e) {
    echo "Error caught!";
} catch (DivisionByZeroError $e) {
    echo "DivisionByZeroError caught!";
}

```

Footnotes 1

[`https://php.net/manual/en/class.throwable.php`](https://php.net/manual/en/class.throwable.php)

  2

[`https://php.net/manual/en/errorfunc.constants.php`](https://php.net/manual/en/errorfunc.constants.php)

  3

[`https://php.net/manual/en/function.set-error-handler.php`](https://php.net/manual/en/function.set-error-handler.php)

  4

[`https://php.net/manual/en/language.types.callable.php`](https://php.net/manual/en/language.types.callable.php)

  5

[`https://php.net/manual/en/function.error-log.php`](https://php.net/manual/en/function.error-log.php)

  6

[`https://rollbar.com/`](https://rollbar.com/)

  7

[`https://php.net/manual/en/errorfunc.configuration.php#ini.error-log`](https://php.net/manual/en/errorfunc.configuration.php#ini.error-log)

  8

[`https://php.net/manual/en/ref.errorfunc.php`](https://php.net/manual/en/ref.errorfunc.php)

  9

[`https://php.net/manual/en/class.throwable.php`](https://php.net/manual/en/class.throwable.php)

  10

[`en.wikipedia.org/wiki/Robustness_(computer_science)`](https://en.wikipedia.org/wiki/Robustness_(computer_science)

  11

[`https://php.net/manual/en/language.exceptions.php`](https://php.net/manual/en/language.exceptions.php)